[main]
    separator = "-"
    description = "Hinode is a clean documentation and blog theme for your Hugo site based on Bootstrap 5."
    enableDarkMode = true
    canonifyAssetsURLs = true

[modules]
    core = ["bootstrap", "flexsearch", "fontawesome"]
    optional = ["leaflet", "katex"]
    excludeSCSS = ["bootstrap"]
    disableTemplate = ["katex"]

[docs]
    contentPath = "/docs/"
    basePath = "_vendor/github.com/gethinode/hinode"
    version = "0.9"
    latest = "1.0"
    checkVersion = true
    latestURL = "https://version-demo.gethinode.com/docs/"
  
[[docs.releases]]
    label = "Current release"

[[docs.releases]]
    label = "0.9"
    url = "/docs/0.9/"
    latest = true

[[docs.releases]]
    label = "Previous releases"

[[docs.releases]]
    label = "v0.2"
    url = "/docs/0.2/"

[[docs.releases]]
    label = "v0.1"
    url = "/docs/0.1/"

[home]
    sections = ["blog", "projects"]
    featurePhoto = "/img/sunrise.jpg" # source: https://unsplash.com/photos/ZX6BPboJrYk
    fullCover = false

[navigation]
    anchor = true
    logo = "/img/logo_icon.svg"
    color = "body"
    style = "light"
    fixed = true
    offset = "3.8em"
    search = true
    breadcrumb = false
    toc = true
    sidebar = true

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[sections]
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 3
        separator = true
    [sections.projects]
        title = "Projects"
        layout = "card"
        sort = "title"
        reverse = false
        nested = true
        cols = 1
        background = "body-tertiary"
        color = "body"
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "horizontal-sm"
        style = "border-1 card-emphasize"
        homepage = 3
        separator = false

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    primary = "#2596be"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    themeFont = "Inter"
    themeFontPath = "/fonts"

[schema]
    type = "Organization"
    name = "Hinode"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    github = "https://github.com/gethinode/hinode"
    section = "blog"
    [author]
        name = "Mark Dumay"
        # twitter = "https://twitter.com/markdumay"
        linkedin = "https://www.linkedin.com/in/markdumay/"
        github = "https://github.com/markdumay"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 

[links]
    bs_badge_heading = "https://getbootstrap.com/docs/5.2/components/badge/#headings"
    hinode_docs = "https://gethinode.com/docs"
    hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
    mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
    observatory = "https://observatory.mozilla.org/analyze/demo.gethinode.com"
    pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.gethinode.com%2F"
    utterances = "https://utteranc.es"
 